### ISSUE TITLE
image v4 support

### ISSUE THREAD

**Issue by alextekartik** [justacid/blurhash-dart#18]
Thanks for your pure dart package.
the image package is now at version 4. Your package depends on version 3. Any chance to get it updated (or to have a version without the image dependency that just encode raw bytes).

I think there is PR for that. Thanks !

**Comment by justacid** [comment]
Yes, there is an open PR - I'll take a look as soon as possible. 
Thanks for your patience! :)

**Comment by justacid** [comment]
I've just released version 1.2.0 to pub with image v4 support, thanks for your patience again!
