### ISSUE TITLE
Widget wrappers for encoding and decoding

### ISSUE THREAD

**Issue by aytunch** [justacid/blurhash-dart#3]
Would it be better to make this package more Flutter friendly by wrapping the example code snippets inside of a Builder Widget?

```
BlurhashDartImage(
    blurhashstring:"abcdef",
    height:300,
    width:200,
    builder:(ctx, widget/image) {
        return blabla;
    })
```

**Comment by justacid** [comment]
I do not want to directly depend on flutter with this package, so that it can also be used in other contexts (e.g, dart server backends). Writing a widget that wraps the decoding is pretty trivial anyways and encoding as a widget does not make much sense in my opinion.

**Comment by aytunch** [comment]
> I do not want to directly depend on flutter with this package, so that it can also be used in other contexts (e.g, dart server backends). Writing a widget that wraps the decoding is pretty trivial anyways and encoding as a widget does not make much sense in my opinion.

@justacid Sounds very reasonable. Thanks:)
