### ISSUE TITLE
Extract color avarages from the BlurHash(for whole image and for seperate sides)

### ISSUE THREAD

**Issue by aytunch** [justacid/blurhash-dart#5]
> [The data representation makes it quite easy to extract colour averages of the image for different areas. You can easily find approximations of things like the average colour of the top edge of the image, or of a corner. There is some code in the Swift BlurHashKit implementation to experiment with this. Also, the average colour of the entire image is just the DC component and can be decoded even without implementing any of the more complicated DCT stuff.](https://github.com/woltapp/blurhash)

They stated that it is "easy" but I could not find a way to extract the main color of an image from the blurhash code. It also says we can easily extract this info for the sides of the image. Reminds me of Phillips ambilight TVs.

This can be a cool feature.

**Comment by justacid** [comment]
As far as I understand, you have to decode the string into its components as seen [here](https://github.com/woltapp/blurhash/blob/master/Swift/BlurHashKit/FromString.swift#L3), then you can extract the average color like seen [here](https://github.com/woltapp/blurhash/blob/master/Swift/BlurHashKit/ColourProbes.swift#L44). Seems easy enough to do, I'll keep it in mind for now.

**Comment by justacid** [comment]
I'm currently working on a new version (1.0.0-dev), which includes some extension methods to extract darkness values, as implemented in the swift version, and exposes the BlurHash components, which can be used for further stuff like that on top. I'll probably not implement anything else, PR's are always welcome though.

**Comment by aytunch** [comment]
@justacid I am glad to hear about version 1.0.0. Do you have any time estimation. And will there be breaking changes? I will update my code accordingly.

**Comment by aytunch** [comment]
@justacid I checked the dev branch and the new Api looks very cool.
I have seen the extension methods for understanding if any part of the BlurHash Image is dark or not.
However I could not see a extension method for getting the avarage color of the total Blur Hash image

> Also, the average colour of the entire image is just the DC component and can be decoded even without implementing any of the more complicated DCT stuff.

Are we supposed to use `ColorTriplet decodeDC(int value)`? If yes, what is the int value?

Finally, will there be a `Punch` value used in the new API as seen in the algorithm?

**Comment by justacid** [comment]
Hi, I don't have a definite timeline yet, sorry! I'm mostly waiting for the image package to release a null-safe version.

Regarding the average color: 
According to the swift implementation (and how I understand it), you literally just take the component at (0, 0) for the average color (I'll have to play with that some more): https://github.com/woltapp/blurhash/blob/6d9bc1ffd1f84593b078e7d1bb35a93123a3ae55/Swift/BlurHashKit/ColourProbes.swift#L44. I'd be happy to expose this, if its working as I believe it does.

> Finally, will there be a Punch value used in the new API as seen in the algorithm?

There is a punch parameter on the encode function. Or are you referring to something different?

**Comment by justacid** [comment]
I just published the first null-safety enabled version, which includes the new utility extensions with documentation.
For example to get the average color you can do something like this:

```
'package:blurhash_dart/blurhash_dart.dart'
'package:blurhash_dart/blurhash_extensions.dart'

const hash = 'LEHV6nWB2yk8pyo0adR*.7kCMdnj';
final blurHash = BlurHash.decode(hash);
final color = blurHash.averageLinearRgb.toRgb();

print('Color(${color.r}, ${color.g}, ${color.b}');
```
