### ISSUE TITLE
BlurHash-dart shadow

### ISSUE THREAD

**Issue by aytunch** [justacid/blurhash-dart#6]
Let's say we use a Stack and place the BlurHash image on bottom and the actual image on top(BlurHash image being a little bigger than the actual image). I haven't tried but just by imagining, this might end up with a cool shadow effect instead of the normal fixed color shadows. Of course in this case we would need to gradually decrease the opacity of the blurhash image for it to look like a real shadow.

**Comment by justacid** [comment]
That's probably easy to do (don't know if it would look good though), but out of scope for this library, as I don't want to offer flutter specific stuff with this package (I'd rather see a separate flutter package). See https://github.com/justacid/blurhash-dart/issues/3#issuecomment-590253923.
